import HealthKit

/// Stable, human-readable names for workout activity types, matching the
/// Swift case names. Types this build doesn't know (newer OS, or long-
/// deprecated cases) serialize as "activity_<rawValue>" rather than being
/// silently merged into "other".
enum WorkoutActivityName {
    static func name(for activity: HKWorkoutActivityType) -> String {
        switch activity {
        case .americanFootball: "americanFootball"
        case .archery: "archery"
        case .australianFootball: "australianFootball"
        case .badminton: "badminton"
        case .barre: "barre"
        case .baseball: "baseball"
        case .basketball: "basketball"
        case .bowling: "bowling"
        case .boxing: "boxing"
        case .cardioDance: "cardioDance"
        case .climbing: "climbing"
        case .cooldown: "cooldown"
        case .coreTraining: "coreTraining"
        case .cricket: "cricket"
        case .crossCountrySkiing: "crossCountrySkiing"
        case .crossTraining: "crossTraining"
        case .curling: "curling"
        case .cycling: "cycling"
        case .discSports: "discSports"
        case .downhillSkiing: "downhillSkiing"
        case .elliptical: "elliptical"
        case .equestrianSports: "equestrianSports"
        case .fencing: "fencing"
        case .fishing: "fishing"
        case .fitnessGaming: "fitnessGaming"
        case .flexibility: "flexibility"
        case .functionalStrengthTraining: "functionalStrengthTraining"
        case .golf: "golf"
        case .gymnastics: "gymnastics"
        case .handball: "handball"
        case .handCycling: "handCycling"
        case .highIntensityIntervalTraining: "highIntensityIntervalTraining"
        case .hiking: "hiking"
        case .hockey: "hockey"
        case .hunting: "hunting"
        case .jumpRope: "jumpRope"
        case .kickboxing: "kickboxing"
        case .lacrosse: "lacrosse"
        case .martialArts: "martialArts"
        case .mindAndBody: "mindAndBody"
        case .mixedCardio: "mixedCardio"
        case .other: "other"
        case .paddleSports: "paddleSports"
        case .pickleball: "pickleball"
        case .pilates: "pilates"
        case .play: "play"
        case .preparationAndRecovery: "preparationAndRecovery"
        case .racquetball: "racquetball"
        case .rowing: "rowing"
        case .rugby: "rugby"
        case .running: "running"
        case .sailing: "sailing"
        case .skatingSports: "skatingSports"
        case .snowboarding: "snowboarding"
        case .snowSports: "snowSports"
        case .soccer: "soccer"
        case .socialDance: "socialDance"
        case .softball: "softball"
        case .squash: "squash"
        case .stairClimbing: "stairClimbing"
        case .stairs: "stairs"
        case .stepTraining: "stepTraining"
        case .surfingSports: "surfingSports"
        case .swimBikeRun: "swimBikeRun"
        case .swimming: "swimming"
        case .tableTennis: "tableTennis"
        case .taiChi: "taiChi"
        case .tennis: "tennis"
        case .trackAndField: "trackAndField"
        case .traditionalStrengthTraining: "traditionalStrengthTraining"
        case .transition: "transition"
        case .underwaterDiving: "underwaterDiving"
        case .volleyball: "volleyball"
        case .walking: "walking"
        case .waterFitness: "waterFitness"
        case .waterPolo: "waterPolo"
        case .waterSports: "waterSports"
        case .wheelchairRunPace: "wheelchairRunPace"
        case .wheelchairWalkPace: "wheelchairWalkPace"
        case .wrestling: "wrestling"
        case .yoga: "yoga"
        default: "activity_\(activity.rawValue)"
        }
    }
}
